CREATE FUNCTION add_one(integer) RETURNS integer
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION copytext(text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION concat_text(text, text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT